### Get all workouts
GET http://localhost:8080/api/workouts

### Get particular workout
GET http://localhost:8080/api/workouts/de1eaf7b-1b68-4c0a-a15e-682da5aa4c66

### Delete workout
DELETE http://localhost:8080/api/workouts/de1eaf7b-1b68-4c0a-a15e-682da5aa4c66